language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 73e11c4f6196eea58dc09e86c3e5c5eb59303863
 local_dir: dist
 on:
   branch: master